services:
  - type: web
    name: meart-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
