services:
  - type: web
    name: meart-app
    env: node
    buildCommand: npm ci && python3 -m pip install --user --no-cache-dir -r requirements.txt
    startCommand: node server.js
    plan: starter
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
