services:
  - type: web
    name: meart-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 70