services:
  - type: web
    name: meart-app
    env: node
    buildCommand: npm ci
    startCommand: node server.js
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
